      PROGRAM globaladj
C     Takes the fortran formated line lists fort.12,fort.99,fort.19,
C     fort.20 and makes global edits to parameters
      PARAMETER (kw=99,mw=139,mw6=mw*6)
      PARAMETER (LENREC=8000,MAXLEN=2000001,MAXPROF=10000,
     1           MAXBUFF=MAXLEN+MAXPROF,MAXLIN=MAXBUFF+MAXPROF*2)
C     LENREC  transposition is done in blocks of LENRECxkw
C     MAXLEN  number of points in the spectrum
C     MAXPROF number of points in either wing of a line with a Voigt profile
      COMMON /BUFFER/BUFFER(MAXBUFF),PROFILE(MAXPROF)
      DIMENSION LINE(MAXLIN)
      DIMENSION TRANSP(kw,LENREC),RECORD(LENREC),INDEXR(5000)
      EQUIVALENCE (BUFFER(1),LINE(1),TRANSP(1))
C      DIMENSION TRANSP(55000,kw)
      COMMON /CONTIN/CONTINUUM(MAXBUFF)
      COMMON /BHE/BHE1(kw,29),AHE1(kw),SHE1(kw),BHE2(kw,6),AHE2(kw),
     1            SHE2(kw),AHEMIN(kw),SIGHE(kw),XNFPHE(kw,3),XNFHE(kw,2)
      COMMON /BHYD/BHYD(kw,8),AHYD(kw),SHYD(kw),AH2P(kw),BMIN(kw),
     1             AHMIN(kw),SHMIN(kw),SIGH(kw),SIGH2(kw),AHLINE(kw),
     2             SHLINE(kw),XNFPH(kw,2),XNFH(kw)
      COMMON /EXTAB/EXTAB(1001),EXTABF(1001),E1TAB(2000)
      COMMON /H1TAB/H0TAB(2001),H1TAB(2001),H2TAB(2001)
      COMMON /LINDAT/WL,E,EP,LABEL(2),LABELP(2),OTHER1(2),OTHER2(2),
     1        WLVAC,CENTER,CONCEN, NELION,GAMMAR,GAMMAS,GAMMAW,REF,
     2      NBLO,NBUP,ISO1,X1,ISO2,X2,GFLOG,XJ,XJP,CODE,ELO,GF,GS,GR,GW,
     3        DWL,DGFLOG,DGAMMAR,DGAMMAS,DGAMMAW,EXTRA1,EXTRA2,EXTRA3
      COMMON /NLINES/WLBEG,WLEND,RESOLU,RATIO,RATIOLG,WBEGIN,
     1               LENGTH,MLINES,IXWLBEG
      COMMON /RHOX/RHOX(kw),NRHOX
      COMMON /STATE/P(kw),XNE(kw),XNATOM(kw),RHO(kw),PTOTAL(kw)
      COMMON /TEMP/T(kw),TKEV(kw),TK(kw),HKT(kw),TLOG(kw),HCKT(kw),ITEMP
      COMMON /TURBPR/VTURB(kw),PTURB(kw),TRBFDG,TRBCON,TRBPOW,TRBSND,
     1               IFTURB
      COMMON /TXNXN/EMERGE(kw),TXNXN(kw),BSTIM(kw),XNFH2(kw)
      COMMON /XNFDOP/XNFPEL(mw6),DOPPLE(mw6),XNFDOP(mw6)
      common /elem/abund(99),atmass(99),elem(99)
      DIMENSION ABLOG(3,377),IFTP(kw),ABMIN(kw),MLINEJ(kw)
      DIMENSION ASYNTH(kw),ALINEC(kw),ASYNCONT(kw),ALINECONT(kw)
      DIMENSION DECKJ(7,kw)
      DIMENSION VELSHIFT(kw),HFIELD(kw)
      DIMENSION TITLE(74),IDMOL(60),MOMASS(60)
      REAL*8 FRQEDG(377),WLEDGE(377),CMEDGE(377),CONFRQ(1131)
      REAL*8 DELEDGE(377),HALFEDGE(377)
      REAL KAPPA0,KAPPA,KAPCEN,KAPMIN
      REAL*8 QT(kw),QTKEV(kw),QTK(kw),QHKT(kw),QTLOG(kw),QHCKT(kw)
      REAL*8 QP(kw),QXNE(kw),QXNATOM(kw),QRHO(kw),QRHOX(kw),QVTURB(kw)
      REAL*8 QXNFH(kw),QXNFHE(kw,2),QXNFH2(kw),QDOPPLE(mw6),QXNFPEL(mw6)
      REAL*8 QABLOG(1131),QXNFDOP(mw6),QCONGF
C      REAL*8 ASYNTH,ALINEC,TITLE,TEFF,GLOG,IDMOL,MOMASS
      REAL*8 ASYNTH
      REAL*8 TITLE,TEFF,GLOG,IDMOL,MOMASS
      dimension hfactor(kw),hefactor(kw),h2factor(kw)
      REAL*8 CONWAV,CONCM,WAVE
      REAL*8 LINDAT8(14)
      REAL*4 LINDAT4(28)
      EQUIVALENCE (LINDAT8(1),WL),(LINDAT4(1),NELION)
      REAL*8 RESOLU,RATIO,RATIOLG,SIGMA2,WLBEG,WLEND,WBEGIN
      REAL*8 EMERGE
      REAL*8 WL,E,EP,WLVAC,CENTER,CONCEN
      REAL*8 LABEL,LABELP,OTHER1,OTHER2
      real*8 wavel
      REAL*8 ISOFRAC, ISOFRACISO1, ISOFRACISO2

      OPEN(UNIT=1,file='fort.1',STATUS='NEW',FORM='UNFORMATTED')
      OPEN(UNIT=1,file='fort.2',STATUS='NEW',FORM='UNFORMATTED')
      OPEN(UNIT=1,file='fort.3',STATUS='NEW',FORM='UNFORMATTED')
      OPEN(UNIT=1,file='fort.4',STATUS='NEW',FORM='UNFORMATTED')

      OPEN(UNIT=12,file='fort.12',STATUS='OLD',FORM='UNFORMATTED')
      OPEN(UNIT=19,file='fort.19',STATUS='OLD',FORM='UNFORMATTED')
      OPEN(UNIT=20,file='fort.20',STATUS='OLD',
     $     FORM='UNFORMATTED',POSITION='REWIND')
      OPEN(UNIT=99,file='fort.99',STATUS='OLD',
     $     FORM='UNFORMATTED',ACCESS='REWIND')

CCCCCCCCCCCCCC

      OPEN(UNIT=93,FILE="fort.93",STATUS='OLD',
     $     FORM='UNFORMATTED',POSITION='REWIND')
      READ(93)NLINES,LENGTH,IFVAC,IFNLTE,N19,TURBV,DECKJ,IFPRED,
     1     WLBEG,WLEND,RESOLU,RATIO,RATIOLG,CUTOFF,LINOUT
      CLOSE(UNIT=93)

      READ(5,*) ISOFRACISO1, ISOFRACISO2, ISOFRAC

      IF(LINOUT.LT.0.)GO TO 3442
        IF(N19.GT.0)THEN
        DO 3440 I=1,N19
          READ(20)LINDAT8,LINDAT4
          READ(19)WL,ELO,GF,NBLO,NBUP,NELION,TYPE,NCON,NELIONX,
     1      GAMMAR,GAMMAS,GAMMAW,NBUFF

          IF(ISO1.EQ.ISOFRACISO1.OR.ISO1.EQ.ISOFRACISO2) THEN
C           DO THE CORRECTION
            GFLOG = LOG10(GF)
            IF(ISO1.EQ.ISOFRACISO1) THEN
              GFLOG = GFLOG+0.005+LOG10(1.0+(1.0/ISOFRAC))
            ENDIF
            IF(ISO1.EQ.ISOFRACISO2) THEN
              GFLOG = GFLOG+1.955+LOG10(1.0+ISOFRAC)
            ENDIF
            GF = 10.0**(GFLOG)
          ENDIF

          WRITE(1)WL,ELO,GF,NBLO,NBUP,NELION,TYPE,NCON,NELIONX,
     1      GAMMAR,GAMMAS,GAMMAW,NBUFF
 3440     WRITE(2)LINDAT8,LINDAT4
        ENDIF

CCCCCCCCCCCCCCCCCC
        IF(NLINES.GT.0)THEN
        DO 3441 I=1,NLINES
          READ(99)LINDAT8,LINDAT4
          READ(12)NBUFF,CONGF,NELION,ELO,GAMRF,GAMSF,GAMWF

          IF(ISO1.EQ.ISOFRACISO1.OR.ISO1.EQ.ISOFRACISO2) THEN
C           DO THE CORRECTION
            FREQ=2.99792458D17/WL
            GF = CONGF*FREQ*1.77245D0/.026538D0
            GFLOG = LOG10(GF)

            IF(ISO1.EQ.ISOFRACISO1) THEN
              GFLOG = GFLOG+0.005+LOG10(1.0+(1.0/ISOFRAC))
            ENDIF
            IF(ISO1.EQ.ISOFRACISO2) THEN
              GFLOG = GFLOG+1.955+LOG10(1.0+ISOFRAC)
            ENDIF

          GF = 10.0**(GFLOG)
          CONGF=.026538D0/1.77245D0*GF/FREQ

          WRITE(3)NBUFF,CONGF,NELION,ELO,GAMRF,GAMSF,GAMWF
 3441     WRITE(4)LINDAT8,LINDAT4
        ENDIF
 3442 CLOSE(UNIT=19)
      CLOSE(UNIT=20)
      CLOSE(UNIT=12)
      CLOSE(UNIT=99)
      CLOSE(UNIT=1)
      CLOSE(UNIT=2)
      CLOSE(UNIT=3)
      CLOSE(UNIT=4)
      CALL EXIT
      END


